networks:
  app:
    driver: bridge

services:
  backend:
    build: 
      context: ./backend
      dockerfile: ./Dockerfile.back
    ports: 
      - 3000:3000
    environment: 
      - HTTP_PORT=3000
      - MONGO_URL=mongodb://root:example@mongo:27017/
      - JWT_SECRET=SECRET
    networks:
      - app

  frontend:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile.front
    ports: 
      - 5173:5173
    volumes:
      - ./frontend:/app
    tty: true
    environment: 
      - VITE_MAIN_URL=http://localhost:3000/api
      - VITE_SERVER_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - app